include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    use_key_in_widget_constructors: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false